title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.4.0

url: https://just-the-docs.github.io
baseurl: "/New_BAI_DateAnalysis"
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
# Optional: If you're having trouble with image paths
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
