title: Data Analysis for Ecologist
description: A tutorial for starters learning how to use python to munipulate climate data!
remote_theme: just-the-docs/just-the-docs

url: https://ericluoyuu.github.io
baseurl: "/New_BAI_DateAnalysis"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-remote-theme

# Just the Docs specific settings
color_scheme: light
search_enabled: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
