name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git reset --hard
          git add -f _site
          git mv _site/* .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
